language: python

sudo: true

dist: bionic

services:
  - docker

env:
  global:
   - CPLUS_INCLUDE_PATH=/usr/include/gdal
   - C_INCLUDE_PATH=/usr/include/gdal

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - docker build -t geopython/stetl:local .
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install -qq build-essential python3-dev python3-setuptools
  - sudo apt-get install -qq python3-lxml libgdal-dev python3-psycopg2 python3-jinja2 gdal-bin

install:
  # follow GDAL installed version for Python bindings
  - pip3 install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`
  - python3 setup.py install
  - pip3 install -r requirements-dev.txt

script:
  - flake8
  - cd docs && make html && cd ..
  - nose2 -v
  - docker run geopython/stetl:local nose2
  - pushd examples/basics && ./runall.sh  && popd
  - pushd examples/basics && ./runall-docker.sh  && popd

# after-script:
#  - python todo


